-- MySQL Script generated by MySQL Workbench
-- 02/06/17 15:26:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DasafioOLX
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DasafioOLX
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DesafioOLX` DEFAULT CHARACTER SET utf8 ;
USE `DesafioOLX` ;

-- -----------------------------------------------------
-- Table `DasafioOLX`.`Tipo_Chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioOLX`.`Tipo_Chamado` (
  `idTipoChamado` INT NOT NULL AUTO_INCREMENT,
  `dscTipoChamado` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoChamado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DasafioOLX`.`Motivo_Chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioOLX`.`Motivo_Chamado` (
  `idMotivoChamado` INT NOT NULL AUTO_INCREMENT,
  `dscMotivoChamado` VARCHAR(45) NULL,
  PRIMARY KEY (`idMotivoChamado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DasafioOLX`.`EstadosBR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioOLX`.`EstadosBR` (
  `idEstadosBR` INT NOT NULL AUTO_INCREMENT,
  `codigoIBGE` INT NULL,
  `sigla` CHAR(2),
  `dscEstado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadosBR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Inserts `DasafioOLX`.`EstadosBR`
-- -----------------------------------------------------
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(12,'AC','Acre');  
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(27,'AL','Alagoas');  
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(13,'AM','Amazonas');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(16,'AP','Amapá');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(29,'BA','Bahia');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(23,'CE','Ceará');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(53,'DF','Distrito Federal');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(32,'ES','Espírito Santo');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(52,'GO','Goiás');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(21,'MA','Maranhão');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(31,'MG','Minas Gerais');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(50,'MS','Mato Grosso do Sul');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(51,'MT','Mato Grosso');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(15,'PA','Pará');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(25,'PB','Paraíba');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(26,'PE','Pernambuco');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(22,'PI','Piauí');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(41,'PR','Paraná');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(33,'RJ','Rio de Janeiro');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(24,'RN','Rio Grande do Norte');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(11,'RO','Rondônia');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(14,'RR','Roraima');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(43,'RS','Rio Grande do Sul');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(42,'SC','Santa Catarina');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(28,'SE','Sergipe');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(35,'SP','São Paulo');
 Insert Into EstadosBR (codigoIBGE,sigla,dscEstado) Values(17,'TO','Tocantins');
 
-- -----------------------------------------------------
-- Inserts `DasafioOLX`.`tipo_chamado`
-- -----------------------------------------------------
Insert into tipo_chamado(dscTipoChamado) values('Telefone');
Insert into tipo_chamado(dscTipoChamado) values('Chat');
Insert into tipo_chamado(dscTipoChamado) values('Email');

-- -----------------------------------------------------
-- Inserts `DasafioOLX`.`motivo_chamado`
-- -----------------------------------------------------
Insert into motivo_chamado(dscMotivoChamado) values('Dúvidas');
Insert into motivo_chamado(dscMotivoChamado) values('Elogios');
Insert into motivo_chamado(dscMotivoChamado) values('Sugestão');


-- -----------------------------------------------------
-- Table `DasafioOLX`.`Chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioOLX`.`Chamados` (
  `idChamados` INT NOT NULL AUTO_INCREMENT,
  `dscDetalhesChamado` VARCHAR(500) NULL,
  `DataChamado` DATETIME NULL,
  `idTipoChamado` INT NOT NULL,
  `idMotivoChamado` INT NOT NULL,
  `idEstadosBR` INT NOT NULL,
  PRIMARY KEY (`idChamados`),
  INDEX `fk_Chamados_Tipo_Chamado_idx` (`idTipoChamado` ASC),
  INDEX `fk_Chamados_Motivo_Chamado1_idx` (`idMotivoChamado` ASC),
  INDEX `fk_Chamados_EstadosBR1_idx` (`idEstadosBR` ASC),
  CONSTRAINT `fk_Chamados_Tipo_Chamado`
    FOREIGN KEY (`idTipoChamado`)
    REFERENCES `DesafioOLX`.`Tipo_Chamado` (`idTipoChamado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chamados_Motivo_Chamado1`
    FOREIGN KEY (`idMotivoChamado`)
    REFERENCES `DesafioOLX`.`Motivo_Chamado` (`idMotivoChamado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chamados_EstadosBR1`
    FOREIGN KEY (`idEstadosBR`)
    REFERENCES `DesafioOLX`.`EstadosBR` (`idEstadosBR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
